name: Update Toulouse Weather Report

on:
  schedule:
    - cron: '0 2,14 * * MON,WED,FRI'
    - cron: '0 6,18 * * TUE,THU,SAT'
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Get Toulouse weather data
      run: ruby ./scripts/api_getter.rb

    - name: Commit and push if README.md has changed
      run: |
        git config user.name "Matthieu-Jck"
        git config user.email "matthieu.jacques.2077@gmail.com"
        git add README.md
        if git diff --staged | grep README.md; then
          git commit -m "Update Toulouse weather report"
          git push
        else
          echo "No changes to commit"
        fi

